FROM node:20

WORKDIR /app

COPY ./services/ttk-collector/package*.json ./
COPY ./prisma ./

RUN npm install 

COPY ./services/ttk-collector ./

RUN npx prisma generate

CMD ["npm", "run", "start:dev"]