version: '3.8'

services:
  publisher:
    image: andriiuni/events
    restart: always
    env_file:
      - .env
    depends_on:
      - gateway
    ports:
      - '8080:8080'

  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    expose:
      - '80'
    depends_on:
      - gateway
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:10.21
    container_name: postgres
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db-migrator:
    build:
      context: .
      dockerfile: ./services/ttk-collector/Dockerfile.dev
    command: npx prisma migrate deploy
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma

  nats:
    image: nats
    container_name: nats
    restart: always
    command: -js -c /etc/nats/nats.conf
    ports:
      - '4222:4222'
    volumes:
      - ./config/nats/nats.conf:/etc/nats/nats.conf
      - nats-data:/data

  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile.dev
    expose:
      - '3000'
    depends_on:
      - postgres
      - nats

  ttk-collector:
    build:
      context: .
      dockerfile: ./services/ttk-collector/Dockerfile.dev
    expose:
      - '3001'
    env_file:
      - .env
    depends_on:
      - gateway

  fb-collector:
    build:
      context: .
      dockerfile: ./services/fb-collector/Dockerfile.dev
    expose:
      - '3002'
    env_file:
      - .env
    depends_on:
      - gateway

  reporter:
    build:
      context: .
      dockerfile: ./services/reporter/Dockerfile.dev
    expose:
      - '3003:3003'
    env_file:
      - .env
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    user: '65534:65534'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - '9090'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3005:3000'
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

volumes:
  postgres-data:
    driver: local
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  nats-data:
    driver: local
